import Head from 'next/head';
import { useState } from 'react';
import Link from 'next/link';
import styles from '../styles/Home.module.css';



export default function Home({lista}) {
    //realiza a busca pegando a query
  const [searchText, setSearchText] = useState('');

    //realiza a seleão de filmes
  const [movieList, setMovieList] = useState([]);


    const search = async () => {
       if(searchText !== '') {
         const result = await fetch(`http://localhost:3000/api/search?q=${searchText}`);  
        const json = await result.json();

        setMovieList(json.list);
        }
    }

    return (
    <div className={styles.container}>
      <Head>
        <title>Lista Filmes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         busca
        </h1>

    <input type='text' value={searchText} onChange={e=>setSearchText(e.target.value)}></input>
    <button onClick={search}>buscar</button>

    
    <ul>
        {movieList.map(item=>(
          <Link href={`/movie/${item.id}`}>
          <li>
            <img src={`https://image.tmdb.org/t/p/original${item.poster_path}`}  width='150' /><br/>
            {item.title}
             
            <span className={styles.span}> nota: {item.vote_average}</span>  
            
          </li>
          </Link>
        ))}
      </ul>


      </main>
    </div>
  )
}
