import Head from 'next/head';
import Link from 'next/link';
import styles from '../../styles/Home.module.css';


export default function MovieInfo(data) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lista Filmes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <h1 className={styles.title}>
            {data.info.title} 
        </h1>

        <img src={`https://image.tmdb.org/t/p/original${data.info.backdrop_path}`}  width='400' /><br/>

<p>{data.info.overview}</p>
        

        
    <button><Link href='/busca'>Página de busca</Link></button>

      </main>
      
    </div>
  )
}

export async function getServerSideProps(context){
  
  const res = await fetch(`http://localhost:3000/api/movie/${context.params.id}`);
  const json = await res.json();

  console.log(json);

  return {
    props: {
      //pegando dados da rota da api
      info: json.list
    }
  };
}